apiVersion: v1
kind: Service
metadata:
  labels:
    app: crud-app-demo-2
  name: crud-app-demo-2
  namespace: dev
spec:
  selector:
    app: crud-app-demo-2
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: LoadBalancer

