apiVersion: v1
kind: Service
metadata:
  labels:
    app: crud-app-demo-1
  name: crud-app-demo-1
  namespace: dev
spec:
  selector:
    app: crud-app-demo-1
  ports:
  - port: 8080
#    targetPort: 8080
    name: http
#  type: LoadBalancer

