apiVersion: v1
kind: Service
metadata:
  labels:
    app: crud-app-demo-1
  name: crud-app-demo-1-service
  namespace: dev
spec:
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: crud-app-demo-1
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

