apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crud-app-demo-1-v1
  namespace: dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: crud-app-demo-1
        version: v1
    spec:
      containers:
      - name: crud-app-demo-1
        image: asia.gcr.io/hip-microservices-experiment-2/crud-demo-app@sha256:c34e849d729087c4cdfb0673ce77b17b52cc2845b77b50b7f186b5cb4b766b59
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2560Mi"
            cpu: "1024m"
          limits:
            memory: "4096Mi"
            cpu: "2048m"
        envFrom:
        - configMapRef:
            name: crud-app-demo-1-config
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: postgres-password
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: postgres-username
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
