kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-db-volume
  namespace: dev
  labels:
    type: local
    app: postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-db-claim
  namespace: dev
  labels:
    app: postgres-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
