apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "postgres-db"
  namespace: "dev"
  labels:
    app: "postgres-db"
    env: "dev"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres-db"
  template:
    metadata:
      labels:
        app: "postgres-db"
        env: "dev"
    spec:
      containers:
      - name: "postgres-db"
        image: "asia.gcr.io/hip-microservices-experiment-2/postgres-db:latest"
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-db-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-db-claim
